---
deployment:
  tasks:
    # 1) Set your deploy path (EDIT THIS: cPanel user + theme folder)
    - export DEPLOYPATH=/home/innovationforumc/public_html/wp-content/themes/innovation-forum

    # 2) Ensure the target exists
    - /bin/mkdir -p "$DEPLOYPATH"

    # 3) (Optional) build steps — uncomment if you commit source not build
    # If you build locally/CI and commit final assets, leave these commented out.
    # - /usr/local/bin/npm ci --omit=dev || true
    # - /usr/local/bin/npm run build || true
    # - /usr/local/bin/composer install --no-dev --prefer-dist --no-interaction || true

    # 4) Sync repo → live theme folder (clean, but safe)
    - /usr/bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".github" \
        --exclude ".cpanel" \
        --exclude "node_modules" \
        --exclude "vendor" \
        --exclude "*.map" \
        ./ "$DEPLOYPATH"/

    # 5) Fix permissions (typical WP-safe defaults)
    - /usr/bin/find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec chmod 644 {} \;

    # 6) (Optional) clear cache, regenerate assets, etc.
    # Requires wp-cli installed on server and correct path to WordPress.
    # - /usr/local/bin/wp cache flush --path=/home/CPANELUSER/public_html || true
